name: Lint, Check Types, Jest
on: push

jobs:
  build:
    name: Lint, Check Types, Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - run: yarn eslint . --max-warnings 0
      - run: yarn tsc
      - run: yarn tsc -p cypress
      # Run the Jest unit tests
      - run: yarn jest
